services:
  app:
    image: chatapp
    build: ./server
    ports:
      - "7888:7888"
    environment:
      MYSQL_HOST: mysql
    depends_on:
      - mysql
    volumes:
    - ./server:/usr/src/app

  mysql:
    build: ./mysql/
    restart: always
    ports:
      - "3307:3306"
    expose:
      - '3306'
    volumes:
      - chatappvolume:/var/lib/mysql

volumes:
  chatappvolume:
